import SiteHome,{Icon,Label,Button,Benefits} from '../components/site-home';
import ContactForm from './contact-form';
import './contact.css';
export const metadata={title:'Contact Us | We Paint Siding',description:'Tell us about your exterior or cabinet painting project. Request a free, no-obligation quote for your home or business across Ontario.'};
const image=(name)=>'/images/contact/'+name+'.webp';
const areas=['Burlington','Oakville','Milton','Hamilton','Guelph','Waterloo','Kitchener','Cambridge','Barrie','London','St. Catharines','Niagara Falls','Welland','Etobicoke','Mississauga','Toronto','North York','Vaughan','Markham','Richmond Hill','Newmarket','Aurora','King City','Caledon','Brantford'];
const services=[{title:'Exterior Painting',image:'house',icon:'home',text:'Enhance curb appeal and protect your property with high-quality exterior painting services.',items:['Spray Painting','Aluminum Painting','Siding Painting','Vinyl Siding Painting','Brick Painting','Exterior Stucco Painting','Wood Siding Painting','Eavestrough & Fascia Painting','Exterior Window & Door Painting','Commercial Painting Service']},{title:'Cabinet Painting',image:'kitchen',icon:'cabinet',text:'Give your kitchen, bathroom, or built-ins a fresh, modern look with professional cabinet painting.',items:['Kitchen Cabinet Painting','Bathroom Vanity Painting','Cabinet Doors & Drawer Fronts','Cabinet Frames, Boxes & End Panels','Built-In Cabinetry']}];
const steps=[['book','Tell Us About Your Project','Fill out our simple form with your project details, location, and what you’d like to have painted.'],['people','We Review the Details','Our team will carefully review your information and get a clear understanding of your project needs.'],['chat','Discuss Your Project','We may get in touch to ask a few questions, discuss the details, and make sure we understand your goals.'],['shield','Move Toward Your Quote','Based on the information gathered, we’ll prepare the next steps and move toward providing your customized quotation.']];
function Areas(){return <ul className="contact-area-list">{areas.map(t=><li key={t}>{t}</li>)}</ul>}
export default function ContactPage(){return <SiteHome isContact>
<section className="section contact-intro"><div className="contact-intro-copy"><Label>01 · CONTACT US</Label><h1>Let’s Talk About Your<br/><em>Painting Project.</em></h1><p>Whether it’s your home or business, we’re here to help bring your vision to life. Fill out the form and request a free, no-obligation quote. Our team will be in touch to learn more about your project and discuss the next steps.</p><Benefits items={ [['home','Exterior Painting'],['cabinet','Cabinet Painting'],['building','Residential & Commercial']] }/><img className="contact-preparation" src={image('tools')} alt="Painting supplies and a ladder prepared beside a home's porch" fetchPriority="high"/></div><ContactForm/></section>
<section id="how-it-works" className="section contact-how"><Label>02 · HOW IT WORKS</Label><div className="contact-section-heading"><h2>What Happens After<br/><em>You Contact Us?</em></h2><p>We’ve made the process simple and straightforward. Here’s what you can expect after you submit your quote request.</p></div><div className="contact-steps">{steps.map(([icon,title,text],i)=><article key={title}><div className="contact-step-icon"><b>0{i+1}</b><Icon name={icon}/></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="contact-how-bottom"><div><Icon name="paint"/><strong>A SMOOTHER EXPERIENCE.<br/>A BRIGHTER RESULT.</strong></div><Button href="#quote">Ready to Get Started? Request Your Free Quote</Button></div></section>
<section id="services-and-areas" className="section contact-services"><Label>03 · SERVICES & SERVICE AREAS</Label><div className="contact-service-heading"><h2>Our Services &<br/><em>Service Areas</em></h2><p>From stunning exteriors to modern cabinet finishes, we provide professional painting services for homes and businesses across Ontario.</p></div><div className="contact-service-layout"><div className="contact-service-cards">{services.map(s=><article key={s.title}><img src={image(s.image)} alt={s.title==='Exterior Painting'?'Freshly painted Ontario home with white siding':'White and navy kitchen with professionally finished cabinetry'} loading="lazy"/><div className="contact-service-content"><Icon name={s.icon}/><h3>{s.title}</h3><p>{s.text}</p><ul>{s.items.map(t=><li key={t}>{t}</li>)}</ul></div></article>)}</div><div className="contact-service-areas"><Label>WHERE WE WORK</Label><h3>Proudly Serving<br/>Communities Across <em>Ontario</em></h3><p>We provide professional painting services to homes and businesses in the following areas:</p><Areas/><Button href="/about#service-areas">View All Service Areas</Button><div className="contact-area-motto"><Icon name="people"/><strong>BEAUTIFUL SPACES.<br/>STRONGER COMMUNITIES.</strong></div></div></div></section>
<section id="contact-next-step" className="section contact-closing"><div className="contact-closing-grid"><div><Label>04 · CONTACT US</Label><h2>Not Sure Where<br/><em>to Start?</em></h2><p>Tell us what you’re working on, where the property is located, and what you’d like to change. We’re here to help and make the process simple.</p><Benefits items={ [['chat','Ask Questions'],['book','Get Expert Advice'],['paint','Take the Next Step']] }/><div className="actions"><Button href="#quote">Request Your Free Quote</Button></div><p className="contact-no-obligation">No obligation. Just a friendly conversation about your project.</p></div><div className="contact-closing-media"><img src={image('house')} alt="White siding home with black windows and a landscaped garden" loading="lazy"/><div className="contact-closing-areas"><Label>SERVING COMMUNITIES ACROSS ONTARIO</Label><Areas/><a className="text-link" href="/about#service-areas">View All Service Areas <span>→</span></a></div></div></div><div className="contact-closing-benefits"><Benefits items={ [['shield','Trusted Local Experts'],['diamond','Quality Craftsmanship'],['people','Serving 25+ Ontario Communities'],['leaf','Beautiful Spaces. Brighter Lives.']] }/></div></section>
</SiteHome>}
