import {notFound} from 'next/navigation';
import SiteHome,{Button,Benefits,Icon} from '../../components/site-home';
import services from '../../data/cabinet-subservices.json';
import '../cabinet.css';
import './cabinet-service.css';
export const dynamicParams=false;
export function generateStaticParams(){return services.map(s=>({service:s.slug}))}
export async function generateMetadata({params}){const {service}=await params;const s=services.find(s=>s.slug===service);return s?{title:s.title+' | We Paint Siding',description:s.tagline+' Professional preparation and a beautiful, durable finish for '+s.surface+'.'}:{}}
function Photo({src,alt,priority=false}){return <img src={src} alt={alt} width={1536} height={1024} loading={priority?undefined:'lazy'} fetchPriority={priority?'high':undefined}/>}
function Band({items}){return <div className="cab-band"><Benefits items={items}/></div>}
function CTA({title,children,process=false}){return <div className="cab-quote-strip"><Icon name="chat"/><div><h3>{title}</h3><p>{children}</p></div><div><Button href="/contact#quote">{process?'Get a Free Quote':'Request a Free Quote'}</Button>{process&&<a className="text-link" href="#cabinet-approach">Learn More About Our Process <span>→</span></a>}</div></div>}
const explanation=[
'Your kitchen cabinets set the tone for the entire space. Over time, they can start to look dated, worn, or no longer match your style. A professional paint finish can completely change the look and feel of your kitchen, brighten the space, and make it feel more modern — without the expense of replacing your cabinets.',
'Our kitchen cabinet painting service is designed to deliver beautiful, long-lasting results. We use high-quality, durable coatings specifically designed for cabinetry, ensuring a smooth, factory-like finish that stands up to daily use.',
'Whether you want a warm, classic look or a clean, contemporary style, we can help you choose the right finish and colour to suit your home. We’ll prepare the cabinets properly, pay attention to every detail, and ensure a professional result you’ll be proud of.',
'Kitchen cabinet painting is a smart investment — it adds value to your home, improves the look and functionality of your kitchen, and lets you enjoy the space again, all at a fraction of the cost of a full remodel.'];
const coverage=[
['cabinet','Cabinet Doors','The most visible part of your kitchen cabinetry, cabinet doors set the style for the entire space. We paint all types of cabinet doors, including shaker, raised panel, flat panel, and more.'],
['drawer','Drawer Fronts','Drawer fronts make up a large portion of your cabinetry and play a key role in the overall appearance. We carefully prepare and paint drawer fronts to ensure a smooth, durable finish that matches your doors.'],
['layers','Cabinet Frames & Boxes','The frames, boxes, and interior visible areas of your cabinets are painted to create a seamless, consistent look. We ensure all exposed surfaces are properly prepared and finished for a uniform appearance.'],
['home','End Panels & Visible Areas','We paint end panels, island panels, and any other visible surfaces to make sure your kitchen has a cohesive, high-quality finish from every angle.']];
const steps=[
['search','Assess','We take the time to understand your existing kitchen cabinets, your goals, and the look you want to achieve. We’ll discuss colour options, finishes, and any specific details for your space.'],
['layers','Prepare','We carefully prepare all cabinet surfaces, including cleaning, sanding, and repairing as needed. We also protect your kitchen space and surrounding areas to ensure a clean, smooth process.'],
['paint','Paint','We apply high-quality, durable cabinet paint using proven techniques to achieve a smooth, factory-like finish. Multiple coats may be applied for the best coverage and long-lasting results.'],
['shield','Refine','We complete a detailed inspection, make any final touch-ups, and ensure every surface meets our high standards — so you can enjoy a beautifully transformed kitchen.']];
const notes=[
['cabinet','Existing Cabinet Condition','Most solid wood, laminate, and thermofoil cabinets can be painted if they are in good structural condition. We’ll assess the condition of your cabinets and let you know if painting is the right option.'],
['layers','Cabinet Configuration','Every kitchen is different. The number of doors, drawer fronts, frames, and visible panels all influence the scope of work. We’ll take the time to understand your kitchen layout and cabinetry details during the quoting process.'],
['paint','Colour and Finish','The right colour can completely change the look and feel of your kitchen. We’ll help you choose a colour and finish that suits your style, complements your home, and provides a durable, long-lasting result.'],
['drawer','Doors and Drawer Fronts','Cabinet doors and drawer fronts are the most visible part of your kitchen cabinets. We carefully prepare and paint all types, including flat panel, raised panel, shaker, and more, to ensure a smooth, factory-like finish.'],
['layers','Frames and Visible Areas','We paint cabinet frames, boxes, end panels, and any other visible surfaces to create a seamless, consistent look throughout your kitchen.'],
['home','Kitchen Layout & Access','We’ll discuss access to your kitchen, protection of surrounding areas, and any specific considerations related to your home. Our team works carefully and efficiently to minimize disruption.'],
['calendar','Project Scope and Timing','The size of your kitchen, number of cabinets, and level of preparation required all influence the timeline. We’ll provide a clear scope of work and let you know what to expect before we get started.'],
['book','Preparing for a Quote','To get an accurate quote, it’s helpful to have a general idea of your goals, preferred colours, and any specific areas you want to include. We’re happy to answer your questions and guide you through the process.'],
['chat','Questions to Ask','Ask about preparation methods, products used, timelines, and what’s included in the quote. A professional cabinet painting service will be transparent, answer your questions, and help you feel confident in your decision.']];
export default async function CabinetServicePage({params}){const {service}=await params;const s=services.find(s=>s.slug===service);if(!s)notFound();const kitchen=s.image==='kitchen';const T=t=>kitchen?t:t.replaceAll('kitchen cabinet painting',s.title.toLowerCase()).replaceAll('Kitchen cabinet painting',s.title).replaceAll('kitchen cabinets',s.surface).replaceAll('kitchen cabinetry',s.surface).replaceAll('Kitchen Layout','Cabinet Layout').replaceAll('Kitchen',s.space.charAt(0).toUpperCase()+s.space.slice(1)).replaceAll('kitchen',s.space);const hero='/images/cabinet/'+s.image+'.webp';const room=kitchen?'Kitchen':s.space.charAt(0).toUpperCase()+s.space.slice(1);const faq=[
[T('What kitchen cabinets can be painted?'),T(notes[0][2])],
['Can cabinet doors and drawer fronts be painted?',T(notes[3][2])],
['Can cabinet frames and boxes be painted?',T(notes[4][2])],
[T('How long does kitchen cabinet painting take?'),T(notes[6][2])],
['What should I do to prepare for the project?','We’ll discuss access, protecting surrounding areas, and preparing your cabinetry before work begins. Follow the preparation instructions provided for your project.'],
['How does the quote process work?',T(notes[7][2])]];
return <SiteHome isCabinet>
<section className="section cab-sub-hero"><div className="cab-split"><div><h1>{s.title}</h1><p className="cab-sub-tagline">{s.tagline}</p><p>{T('Transform your kitchen with professionally painted cabinets. Our kitchen cabinet painting service gives you a beautiful, durable finish at a fraction of the cost of replacing your cabinets — with less disruption and more value for your home.')}</p><div className="actions"><Button href="/contact#quote">Get a Free Quote</Button></div><p className="cab-sub-assurance">No obligation. Just expert advice.</p><Band items={ [['layers','A Cost-Effective Upgrade'],['clock','Less Disruption Than a Remodel'],['shield','A Beautiful, Durable Finish'],['home','Increases Your Home’s Appeal']] }/></div><Photo src={hero} alt={s.title+' illustrative finished cabinetry'} priority/></div></section>
<section className="section"><div className="cab-sub-explanation"><div><h2>A Fresh {room} Starts <em>With the Cabinets.</em></h2><p>{T('Kitchen cabinet painting is one of the most effective ways to transform your kitchen. It gives you a clean, modern look without the cost, construction, and disruption of a full renovation.')}</p><div className="cab-sub-copy">{explanation.map(p=><p key={p}>{T(p)}</p>)}</div></div><aside className="cab-sub-quote"><blockquote>“A well-painted {s.space} can feel like a brand new space.”</blockquote><p>With the right colour and finish, your existing cabinets can look modern, clean, and completely renewed — without the cost of a full renovation.</p></aside></div><Band items={ [['diamond','Modern Look',T('Update the style of your kitchen without replacing your cabinets.')],['layers','Cost-Effective','Get a high-end look for a fraction of the cost of a full renovation.'],['clock','Less Disruption','A faster, cleaner process with less mess and inconvenience.'],['home','Adds Value',T('A fresh, modern kitchen can increase the appeal and value of your home.')] ]}/></section>
<section className="section"><h2>What We Paint {kitchen?'in a Kitchen.':<em>For Your Cabinetry.</em>}</h2><p>{T('We paint all the key components of your kitchen cabinetry to create a clean, consistent, high-quality finish that transforms the look and feel of your space.')}</p><div className="cab-sub-four">{coverage.map(([icon,title,copy])=><article key={title}><Icon name={icon}/><h3>{title}</h3><p>{T(copy)}</p></article>)}</div><CTA title={T('Let’s Bring Your Kitchen to Life.')} process>{T('Contact us today to get started on your kitchen cabinet painting project.')}</CTA></section>
<section className="section"><h2>Real Transformations. <em>A Brighter {room}.</em></h2><p>{T('See how a professional cabinet painting service can completely change the look and feel of a kitchen.')}</p><div className="cab-three cab-transformations">{['From dark and dated to light and modern — a fresh, timeless look for the heart of the home.','A brighter, cleaner finish that enhances the space while keeping the same great layout.','An updated finish that refreshes the space and gives the kitchen a clean, contemporary feel.'].map((copy,i)=><article key={copy}><div className="cab-comparison"><Photo src={kitchen?'/images/cabinet-subservices/comparison-'+(i+1)+'.webp':'/images/cabinet/before-'+['kitchen','vanity','builtins'][i]+'.webp'} alt={'Illustrative cabinet painting before and after concept '+(i+1)}/><span>Before</span><span>After</span><b aria-hidden="true">→</b></div><h3>Transformation 0{i+1}</h3><p>{T(copy)}</p></article>)}</div><p className="cab-image-note">Illustrative cabinetry transformations, not client project photographs.</p><CTA title="Let’s Make It Happen.">{T('Get a free, no-obligation quote for your kitchen cabinet painting project.')}</CTA></section>
<section id="cabinet-approach" className="section"><h2>Our Simple, <em>Professional Process.</em></h2><p>A clear, step-by-step approach to a beautifully painted {s.space}.</p><div className="cab-sub-four cab-sub-process">{steps.map(([icon,title,copy],i)=><article key={title}><div className="cab-sub-step"><b>0{i+1}</b><Icon name={icon}/></div><h3>{title}</h3><p>{T(copy)}</p></article>)}</div><div className="cab-sub-detail-photos"><Photo src="/images/cabinet-subservices/preparation.webp" alt="Careful preparation of a detached cabinet door"/><Photo src="/images/cabinet-subservices/finish.webp" alt="Smooth sage blue cabinet paint finish and brass hardware"/></div><CTA title="Get Started Today.">{T('Contact us for a free, no-obligation quote and discover how kitchen cabinet painting can transform your home.')}</CTA></section>
<section className="section"><h2>Before You Paint Your {kitchen?'Kitchen Cabinets':<em>Cabinetry</em>}, <em>Know What Matters.</em></h2><p>{T('A little planning goes a long way. Here are the key things homeowners should consider before starting a kitchen cabinet painting project.')}</p><div className="cab-sub-notes-layout"><div className="cab-sub-notes">{notes.map(([icon,title,copy],i)=><article key={title}><Icon name={icon}/><h3>{i+1}. {T(title)}</h3><p>{T(copy)}</p></article>)}</div><aside className="cab-sub-quote"><h3>A Well-Painted {room} Adds Lasting Value.</h3><p>{T('Kitchen cabinet painting is a smart investment that enhances the look and functionality of your kitchen — without the cost and disruption of a full remodel.')}</p><ul><li>Understand your options.</li><li>Make informed decisions.</li><li>Get the best results for your home.</li></ul><h3>Have Questions?</h3><p>{T('We’re here to help. Contact us today to discuss your kitchen cabinet painting project.')}</p><a className="text-link" href="/contact">Contact Us <span>→</span></a></aside></div></section>
<section className="section"><div className="cab-sub-final-layout"><div><h2>Frequently Asked <em>Questions</em></h2><p>Quick answers to common questions about {s.title.toLowerCase()}.</p><div className="cab-faq-grid cab-sub-faq">{faq.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div><aside className="cab-sub-final"><Photo src={hero} alt={s.title+' finished cabinet example'}/><div><h2>Ready for a <em>Fresh {room}?</em></h2><p>{T('Let’s bring new life to your kitchen cabinets. Contact us today for a free, no-obligation quote and take the first step toward a brighter, more beautiful kitchen.')}</p><Button href="/contact#quote">Request a Free Quote</Button><Benefits items={ [['shield','No Obligation'],['calendar','Flexible Scheduling'],['people','Friendly, Local Team']] }/></div></aside></div><Band items={ [['phone','Have Questions?','We’re here to help. Give us a call or send us a message.'],['mail','Prefer to Email?','Reach out anytime and we’ll get back to you soon.'],['home','Proudly Serving Your Area','Local, reliable, and committed to quality cabinet painting.']] }/></section>
</SiteHome>}
