import {Button,Benefits,Icon} from '../components/site-home';
import locations from '../data/locations.json';
export {Button,Benefits,Icon,locations};
export function Photo({name,priority=false}){const alts={exterior:'Fresh slate blue siding and white trim on a landscaped Ontario home',cabinet:'White painted kitchen cabinets with a navy island and quartz counters',interior:'Freshly painted living room with white trim and blue cushions',community:'Illustrative Southern Ontario residential neighbourhood with mature trees and maintained homes'};return <img src={'/images/locations/'+name+'.webp'} alt={alts[name]} width={name==='community'?1774:1536} height={name==='community'?887:1024} loading={priority?undefined:'lazy'} fetchPriority={priority?'high':undefined}/>}
export function Map({city='Southern Ontario'}){return <iframe className="location-map" title={'Map of '+city+', Ontario service area'} src={'https://www.google.com/maps?q='+encodeURIComponent(city==='Southern Ontario'?'Southern Ontario, Canada':city+', Ontario, Canada')+'&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>}
export function Band({items}){return <div className="location-band"><Benefits items={items}/></div>}
export function Directory({detail=false}){return <ul className="location-directory">{locations.map(({name,slug})=><li key={slug}><a href={'/locations/'+slug}><div><strong>{name}</strong>{detail&&<small>Exterior Painting · Cabinet Painting</small>}</div><span aria-hidden="true">→</span></a></li>)}</ul>}
export function Help({title,children}){return <aside className="location-help"><Icon name="chat"/><h3>{title}</h3><p>{children}</p><Button href="/contact#quote">Get a Free Quote</Button></aside>}
export function Cards({items,columns=3}){return <div className={'location-cards columns-'+columns}>{items.map(([icon,title,text])=><article key={title}><Icon name={icon}/><h3>{title}</h3><p>{text}</p></article>)}</div>}
export function Services({city,second=false}){const n=city;const entries=second?[
['exterior','Exterior Painting',`Enhance curb appeal and protect your ${n} property with professional exterior painting. We paint siding, brick, stucco, trim, doors, and more, using high-quality products for a durable, long-lasting finish.`,'/exterior-painting'],
['cabinet','Cabinet Painting',`Give your kitchen, bathroom, or built-in cabinets a fresh, modern look. Our cabinet painting services in ${n} deliver a smooth, factory-like finish without the cost and disruption of a full replacement.`,'/cabinet-painting'],
['interior','Interior & Specialized Painting',`From interior walls and ceilings to trim, doors, and specialty finishes, we provide professional painting services for ${n} homes and properties. We also offer additional services such as deck and fence painting to complete your project.`,'/contact#quote']]:[
['exterior','Exterior Painting',`Enhance the look and protection of your home with professional exterior painting services in ${n}. We work with a variety of surfaces, including siding, brick, stucco, trim, and more.`,'/exterior-painting'],
['cabinet','Cabinet Painting',`Update your kitchen, bathroom, or built-in cabinetry with a smooth, durable finish. Our cabinet painting services in ${n} deliver a clean, modern look without the cost of a full remodel.`,'/cabinet-painting'],
['interior','Interior & Specialized Painting',`From interior walls and ceilings to trim, doors, and specialty finishes, we provide high-quality painting services for ${n} homes. We also offer additional services such as deck and fence painting.`,'/contact#quote']];return <div className="location-services">{entries.map(([image,title,copy,href])=><article key={title}><Photo name={image}/><div><h3>{title}</h3><p>{copy}</p><a className="text-link" href={href}>Explore {image==='interior'?'Interior Painting':title} <span>→</span></a></div></article>)}</div>}
