import SiteHome,{Button,Benefits,Icon} from '../components/site-home';
import Comparison from './comparison';
import './before-after.css';
export const metadata={title:'Before and After | We Paint Siding',description:'Explore exterior and cabinet painting transformations with interactive before and after comparisons.'};
const exterior=[['siding','home','Siding Painting','A fresh, modern finish that enhances curb appeal and protects for years.'],['brick','brick','Brick Painting','Transform the look of your home with a clean, updated finish.'],['stucco','paint','Stucco Painting','Refresh and modernize your exterior with a smooth, lasting finish.'],['wood','layers','Wood Siding Painting','Restore and protect your wood siding with a durable, beautiful finish.']];
const cabinets=[['kitchen','cabinet','Kitchen Cabinet Painting','A brighter, more modern kitchen with a smooth, durable finish.'],['vanity','drawer','Bathroom Vanity Painting','A fresh, updated look that adds style and value to your bathroom.'],['builtins','cabinet','Built-In Cabinet Painting','Refresh your built-ins with a clean, modern finish that fits your style.']];
const more=[['siding','Vinyl Siding Painting'],['brick','Brick Painting'],['door','Front Door Painting'],['garage','Garage Door Painting'],['deck','Deck & Fence Painting'],['interior','Interior Wall Painting'],['trim','Trim & Soffit Painting'],['kitchen','Cabinet Door Painting']];
const steps=[['search','Assessment & Planning','We inspect the surfaces, understand the condition and discuss your goals to create the right plan.','/images/about/team.webp'],['layers','Surface Preparation','We clean, repair and prep every surface properly. Good preparation helps paint adhere and last much longer.','/images/cabinet-subservices/preparation.webp'],['paint','Quality Paint & Materials','We use high-quality, professional-grade paints and materials suited for your specific surface and environment.','/images/v2/tools.webp'],['paint','Professional Application','Our experienced team applies the paint with care and consistency for a smooth, even and durable finish.','/images/v2/painter.webp'],['shield','Final Review & Clean-Up','We inspect every detail, make sure you’re happy with the results, and leave your property clean and ready to enjoy.','/images/before-after/siding-after.webp']];
function Band({items}){return <div className="ba-band"><Benefits items={items}/></div>}
function Cards({items}){return <div className={'ba-card-grid '+(items.length===3?'ba-three':'ba-four')}>{items.map(([name,icon,title,copy])=><article key={name}><Comparison name={name} title={title}/><div className="ba-caption"><Icon name={icon}/><div><h3>{title}</h3><p>{copy}</p></div></div></article>)}</div>}
function Project({number,name,title,details}){return <article className="ba-project"><Comparison name={name} title={title}/><div><p className="ba-project-number">Project {number}</p><h3>{title}</h3><dl>{details.map(([icon,label,copy])=><div key={label}><Icon name={icon}/><div><dt>{label}</dt><dd>{copy}</dd></div></div>)}</dl></div></article>}
export default function BeforeAfterPage(){return <SiteHome isBeforeAfter>
<section className="section ba-hero"><div className="ba-split"><div><h1>See the Difference <em>A Fresh Finish Can Make.</em></h1><p>Explore real transformations and see how professional painting can completely refresh the look of your home or business. Same property. A whole new look.</p><p className="ba-image-note">Images show generated transformation concepts, not documented client projects.</p><div className="actions"><Button href="/contact#quote">Get a Free Quote</Button><Button href="#painting-transformations" outline>Explore Our Services</Button></div></div><Comparison name="siding" title="Exterior siding transformation" priority/></div><Band items={ [['paint','Professional Results','A noticeable difference in every project.'],['home','Exterior & Cabinet Transformations','Real projects. Real results.'],['shield','Trusted Local Team','Quality you can see and count on.'],['people','Beautiful Homes & Spaces','Helping our communities look their best.']] }/></section>
<section id="painting-transformations" className="section"><h2>Exterior Painting <em>Transformations</em></h2><p>See how a professional paint finish can completely change the look of a home. From siding and brick to stucco and trim, our exterior painting services bring new life to properties across our service areas.</p><Cards items={exterior}/><Band items={ [['shield','Enhanced Curb Appeal','A fresh exterior makes a lasting impression.'],['home','Added Protection','Quality paint helps protect against Ontario’s weather.'],['clock','Longer Lasting Results','Professional application for long-term performance.'],['star','Homes We’re Proud Of','Real transformations. Real communities.']] }/></section>
<section className="section"><h2>Cabinet Painting <em>Transformations</em></h2><p>Give your kitchen, bathroom or built-in cabinetry a fresh new look without the cost of a full replacement. Our cabinet painting services deliver a modern, durable finish that completely transforms your space.</p><Cards items={cabinets}/><Band items={ [['diamond','Cost-Effective Upgrade','A brand new look without the cost of replacement.'],['paint','Smooth, Durable Finish','High-quality paints for long-lasting results.'],['clock','Minimal Disruption','A faster, cleaner process compared to full renovation.'],['home','A More Beautiful Home','Spaces you’ll love for years to come.']] }/></section>
<section className="section"><h2>Real Projects. <em>Real Details.</em></h2><p>Every property is different. Here are a few example projects that show the scope, process, and results of our exterior and cabinet painting services.</p><div className="ba-project-grid"><Project number="01" name="siding" title="Exterior Siding Painting" details={ [['home','Property Type','Two-storey detached home'],['paint','Scope of Work','Siding, trim, soffits and fascia'],['diamond','Goal','Refresh the exterior and improve curb appeal with a modern colour.'],['check','Result','A clean, modern finish that completely transformed the look of the home.']] }/><Project number="02" name="kitchen" title="Kitchen Cabinet Painting" details={ [['home','Property Type','Residential kitchen'],['paint','Scope of Work','Cabinet doors, drawer fronts and visible frames'],['diamond','Goal','Give the kitchen a fresh, modern look without a full replacement.'],['check','Result','A brighter, more modern space with a smooth, durable finish.']] }/></div><Band items={ [['diamond','Real Projects','Completed across 25 communities.'],['people','Same High Standards','No matter the size or scope.'],['shield','Quality You Can See','In every detail.'],['home','Transformations You Can Trust','Real homes. Real results.']] }/></section>
<section className="section"><h2>More Painting <em>Transformations</em></h2><p>From exteriors to interiors, explore more real examples of how a professional paint finish can refresh, protect, and add value to your property.</p><div className="ba-more-grid">{more.map(([name,title])=><article key={title}><Comparison name={name} title={title}/><h3>{title}</h3></article>)}</div><Band items={ [['paint','Real Transformations','See the difference for yourself.'],['home','Wide Range of Projects','Exteriors, interiors and more.'],['diamond','Quality You Can See','Professional results that last.'],['star','Proudly Serving Our Communities','Beautiful homes. Stronger neighbourhoods.']] }/></section>
<section className="section"><h2>What Goes Into <em>the Transformation</em></h2><p>A beautiful, long-lasting finish is the result of more than just paint. Here’s what goes into every successful exterior or cabinet painting project.</p><div className="ba-process-grid">{steps.map(([icon,title,copy,src],i)=><article key={title}><div className="ba-step-top"><b>0{i+1}</b><Icon name={icon}/></div><h3>{title}</h3><p>{copy}</p><img src={src} alt={title+' illustrative painting process'} width="1536" height="1024" loading="lazy"/></article>)}</div><Band items={ [['shield','Proven Process','A step-by-step approach that delivers real results.'],['people','Experienced Team','Skilled, detail-focused professionals.'],['diamond','Quality Materials','Trusted brands for a long-lasting finish.'],['home','Results You’ll Love','A fresher, more beautiful property.']] }/></section>
<section className="section ba-final"><div className="ba-split"><div><h2>Ready to See What a <em>Fresh Finish Could Do</em> for Your Property?</h2><p>A professional paint finish can completely transform the look, feel and value of your home. Whether it’s your exterior, cabinets or both, our team is ready to help you bring your vision to life.</p><div className="actions"><Button href="/contact#quote">Get a Free Quote</Button><Button href="#painting-transformations" outline>Explore Our Services</Button></div><Benefits items={ [['shield','Professional & Reliable'],['people','Proudly Serving Ontario Communities'],['home','High-Quality, Long-Lasting Results']] }/></div><img src="/images/before-after/siding-after.webp" alt="Illustrative freshly painted slate-blue Ontario home" width="1536" height="1024" loading="lazy"/></div><Band items={ [['paint','Transform Your Space','A fresh, modern look for years to come.'],['clock','Flexible Scheduling','We work around your timeline.'],['diamond','Trusted Local Team','Quality you can count on.'],['home','Results You’ll Love','Beautiful homes. Stronger communities.']] }/></section>
</SiteHome>}
