import {notFound} from 'next/navigation';
import SiteHome from '../../components/site-home';
import {locations,Button,Band,Photo,Map,Help,Cards,Services} from '../shared';
import '../locations.css';
export const dynamicParams=false;
export function generateStaticParams(){return locations.map(({slug})=>({location:slug}))}
export async function generateMetadata({params}){const {location}=await params;const city=locations.find(l=>l.slug===location);return city?{title:`Painting Services in ${city.name} | We Paint Siding`,description:`Professional exterior, interior and cabinet painting in ${city.name}, Ontario. Explore local services, project considerations and request a free quote.`}:{};}
const nearbyGroups=[['Burlington','Oakville','Milton','Hamilton','Brantford'],['Guelph','Waterloo','Kitchener','Cambridge','London'],['St. Catharines','Niagara Falls','Welland','Hamilton'],['Etobicoke','Mississauga','Toronto','North York','Vaughan'],['Markham','Richmond Hill','Newmarket','Aurora','King City','Barrie','Caledon']];
export default async function LocationPage({params}){const {location}=await params;const place=locations.find(l=>l.slug===location);if(!place)notFound();const c=place.name;const burlington=c==='Burlington';const nearby=burlington?['Oakville','Milton','Hamilton','Waterdown','Dundas','Ancaster','Stoney Creek']:(nearbyGroups.find(g=>g.includes(c))||[]).filter(n=>n!==c);const linkFor=n=>{const entry=locations.find(l=>l.name===n);return entry?'/locations/'+entry.slug:'/locations/hamilton'};
const planning=[
['home','Understand Your Property',burlington?'Burlington is home to a mix of property types — from established neighbourhoods to modern builds near the waterfront. The age, materials, and condition of your home all play a role in the right painting approach, whether it’s exterior siding, brick, stucco, or interior spaces.':`${c} is home to a mix of property types — from established neighbourhoods to modern builds. The age, materials, and condition of your home all play a role in the right painting approach, whether it’s exterior siding, brick, stucco, or interior spaces.`],
['paint','Consider Colour and Finish',`${c} homeowners often choose colours that complement the natural surroundings, from modern, neutral palettes to bold accent colours. We’ll guide you through colour options and finishes that suit your property, style, and long-term maintenance goals.`],
['shield','Prepare for a Lasting Result',`Proper surface preparation, high-quality materials, and professional application make a big difference. Our team takes the time to do it right, so your paint looks great and stands up to everyday life — and ${c}’s changing seasons.`],
['paint','Choose the Right Service','Whether you’re refreshing your home’s exterior, updating interior living spaces, or renovating your kitchen with cabinet painting, it’s important to match the service to your goals. A professional assessment can help you determine the best approach for your property.'],
['calendar','Plan for the Scope and Timeline','The size of your home, the number of surfaces, and the level of preparation required all influence the timeline. We’ll provide a clear outline of the work involved so you know what to expect before we get started.'],
['people','Get the Right Information for a Quote',`When requesting a quote, it’s helpful to share details about your property, the areas you want to paint, your goals, and any specific considerations. This helps us provide an accurate quote and recommend the best solutions for your ${c} home.`]];
const considerations=[
['home','Property Type',burlington?'Burlington has a diverse mix of homes, from established neighbourhoods and lakefront properties to modern condos and townhomes. The type, age, and construction of your property can influence the best painting approach.':`${c} has a diverse mix of homes, from established neighbourhoods to modern condos and townhomes. The type, age, and construction of your property can influence the best painting approach.`],
['clock','Interior vs. Exterior','Exterior projects require weather-appropriate timing and surface preparation, while interior projects focus on minimizing disruption and achieving clean, durable finishes inside your home.'],
['paint','Existing Surfaces','We assess the current condition of siding, trim, doors, walls, or cabinetry to determine the right preparation and products for a long-lasting result.'],
['layers','Colour and Finish Goals','Whether you’re refreshing with a modern colour palette or matching existing finishes, we can help you choose colours and sheens that suit your property and style.'],
['calendar','Project Scope and Timeline','The size of your project, level of preparation, and seasonal conditions all play a role in the timeline. We’ll provide a clear estimate of the work involved so you know what to expect.'],
['home','Access and Surroundings','For exterior projects, factors like landscaping, driveways, and nearby structures are considered to ensure a safe and efficient process.'],
['cabinet','Cabinet Condition','If you’re planning a kitchen or bathroom cabinet painting project, we’ll assess the condition, material, and layout to recommend the best approach for a smooth, factory-like finish.'],
['book','Preparing for a Quote','Helpful information includes the type of surfaces, areas you want to paint, your goals, and any specific concerns. Photos are always useful if available.']];
const faq=[
[`Do you provide painting services in ${c}?`,`Yes. We provide professional exterior, interior, cabinet, and specialty painting services throughout ${c} and the surrounding communities.`],
[`What painting services are available in ${c}?`,`We offer exterior painting, interior painting, cabinet painting, and a range of specialty painting services for residential and commercial properties in ${c}.`],
[`Do you offer both residential and commercial painting in ${c}?`,'Yes. We work with homeowners, property managers, and business owners on projects of all sizes, from single-family homes to multi-unit buildings and commercial spaces.'],
[`How do I request a quote for a painting project in ${c}?`,'Contact us to discuss your project. We’ll ask a few questions about your project and arrange a time to provide a detailed, no-obligation quote.'],
['How long does a typical painting project take?','Timelines depend on the size of the property and the scope of work. After we understand your project details, we’ll provide a clear estimate of the expected timeline.'],
['Do you use high-quality paints and materials?',`Yes. We use high-quality, professional-grade products chosen for durability and long-lasting results, with finishes that are well-suited to ${c}’s climate and property types.`]];
return <SiteHome isLocation>
<section className="section location-hero"><div className="location-split"><div><h1>Professional Painting Services in <em>{c}</em></h1><p>{burlington?'From beautiful homes in established neighbourhoods to modern properties near the lake, we provide high-quality exterior, interior, and cabinet painting services throughout Burlington.':`From beautiful homes in established neighbourhoods to modern properties, we provide high-quality exterior, interior, and cabinet painting services throughout ${c}.`}</p><div className="actions"><Button href="/contact#quote">Get a Free Quote</Button><Button href="#local-services" outline>Explore Our Services</Button></div><Band items={ [['home','Residential Painting'],['building','Exterior & Interior Painting'],['cabinet','Cabinet Painting'],['people','Local & Reliable']] }/></div><Photo name="community" priority/></div><Band items={ [['leaf','Beautiful Homes. Stronger Communities.'],['people',`Proudly Serving ${c} Homeowners`],['paint','Quality Painting. Lasting Results.']] }/></section>
<section id="local-services" className="section"><h2>Painting Services in <em>{c}</em></h2><p>Professional painting services for homes and properties throughout {c}.</p><div className="location-content-aside"><Services city={c}/><aside className="location-help"><h3>Additional Services</h3><ul className="location-extra">{['Deck & Fence Painting','Door Painting','Trim & Millwork Painting','Stucco Painting','Siding Painting','Garage Door Painting'].map(t=><li key={t}><a href={t==='Stucco Painting'?'/exterior-painting/exterior-stucco-painting':t==='Siding Painting'?'/exterior-painting/siding-painting':'/contact#quote'}>{t}<span>→</span></a></li>)}</ul><h4>Not sure what you need?</h4><p>We’re here to help. <a href="/contact">Contact us for a free consultation.</a></p></aside></div><Band items={ [['home',`Proudly Serving ${c} & Surrounding Areas`],['people','Experienced. Reliable. Local.'],['shield','Quality Work. A Brighter Tomorrow.']] }/></section>
<section className="section"><h2>Planning a Painting Project in <em>{c}?</em> Start With the Property.</h2><p>Every property is different. Here’s what {c} homeowners should know when planning an exterior, interior, or cabinet painting project.</p><div className="location-content-aside"><Cards items={planning}/><div><Photo name="community"/><Help title={`Have Questions About Your ${c} Property?`}>We’re here to help. Contact us for a free, no-obligation quote and expert advice on your painting project.</Help></div></div><Band items={ [['leaf','Homes of All Styles','From established to modern.'],['home','Local Knowledge',`We understand ${c} properties.`],['shield','Quality You Can Trust','Professional painting for lasting results.']] }/></section>
<section className="section"><h2>Our Painting Services for <em>{c} Properties.</em></h2><p>High-quality painting services designed for {c} homes and properties.</p><div className="location-content-aside"><Services city={c} second/><div><Photo name="community"/><Help title={`Serving ${c} Homes and Businesses`}>No matter the size or style of your property, we provide reliable, high-quality painting services throughout {c}.</Help></div></div><Band items={ [['people','Local Experience',`We understand ${c} properties.`],['shield','Quality Workmanship','A smooth process and lasting results.'],['leaf','A Brighter Community',`Proud to help keep ${c} beautiful.`]] }/></section>
<section className="section"><h2>A Painting Project Should <em>Fit the Property.</em></h2><p>Every property in {c} is unique. Here are some important considerations to keep in mind as you plan your painting project.</p><div className="location-content-aside"><Cards columns={2} items={considerations}/><div><Photo name="community"/><Help title="Not Sure Where to Start?">We’re here to help. Contact us for a free, no-obligation quote and expert advice on your {c} property.</Help></div></div><Band items={ [['people','Local Knowledge',`We understand ${c} properties.`],['shield','Professional Guidance','From planning to the final coat.'],['leaf','Lasting Results','Quality painting for years to come.']] }/></section>
<section className="section"><h2>Proudly Serving <em>{c} & Nearby</em> Communities.</h2><p>We provide professional painting services throughout {c} and the surrounding areas, helping homeowners and businesses improve and protect their properties.</p><div className="location-split"><div className="location-nearby"><div><h3>{c}</h3><p>{burlington?'From the lakeshore to established neighbourhoods, we’re proud to serve the Burlington community with reliable, high-quality painting services.':`From established neighbourhoods to modern properties, we’re proud to serve the ${c} community with reliable, high-quality painting services.`}</p><h3>Nearby Communities</h3><p>We also work in nearby cities and towns, making it easy to access the same professional painting services throughout the surrounding area.</p><Button href="/locations">View All Locations</Button></div><div><h3>Nearby Communities We Serve</h3><ul className="location-extra">{nearby.map(n=><li key={n}><a href={linkFor(n)}>{n}<span>→</span></a></li>)}</ul><h4>Don’t see your community listed?</h4><p><a href="/contact">Contact us to find out if we provide painting services in your area.</a></p></div></div><Map city={c}/></div><Band items={ [['home','Local Service',`In ${c} and surrounding areas.`],['people','Reliable & Professional','Quality painting you can count on.'],['shield','Stronger Communities','Proud to help keep local properties beautiful.']] }/></section>
<section className="section"><h2>{c} <em>Painting FAQ</em></h2><p>Answers to common questions about our painting services in {c}.</p><div className="location-split"><div className="location-faq">{faq.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div><div><Photo name="community"/><Help title={`Planning a Painting Project in ${c}?`}>Let’s talk about your project. Contact us today for a free, no-obligation quote and expert advice from a local team that understands {c} properties.</Help></div></div><Band items={ [['people','Local Experience',`We understand ${c} homes and properties.`],['shield','Professional Service','A smooth process from start to finish.'],['leaf','Lasting Results','Quality painting for a brighter tomorrow.']] }/></section>
<section className="section"><div className="location-split"><div><h2>Professional Painting <em>Close to Home.</em></h2><p>{burlington?'From lakeside homes to established neighbourhoods, we provide reliable, high-quality painting services throughout Burlington and the surrounding communities. Whatever your project, our team is here to help from start to finish.':`From modern homes to established neighbourhoods, we provide reliable, high-quality painting services throughout ${c} and the surrounding communities. Whatever your project, our team is here to help from start to finish.`}</p><Cards columns={4} items={ [['home','Local Knowledge',`We understand ${c} properties and the unique needs of the area.`],['shield','Quality Workmanship','Professional preparation, premium materials, and a clean, careful process.'],['people','Friendly, Reliable Team','Clear communication and a smooth experience from your first call to final walkthrough.'],['leaf','A Brighter Tomorrow','Well-maintained properties help build stronger, more vibrant communities.']] }/><div className="actions"><Button href="/contact#quote">Request a Free Quote</Button><Button href="/contact" outline>Contact Us</Button></div></div><Photo name="community"/></div><div className="location-closing-links">{[['Exterior Painting','Enhance and protect your property.','/exterior-painting'],['Cabinet Painting','Beautiful, durable finishes for your kitchen and beyond.','/cabinet-painting'],['All Locations','View our full list of service areas.','/locations'],['Contact Us','Get in touch with our team.','/contact']].map(([t,d,h])=><a key={t} href={h}><strong>{t}</strong><p>{d}</p><span>→</span></a>)}</div></section>
</SiteHome>}
