import {notFound} from 'next/navigation';
import SiteHome from '../../components/site-home';
import posts from '../../data/blog-posts.json';
import {readingTime,PostCard,BlogCTA} from '../shared';
import '../../support/support.css';
export const dynamicParams=false;
export function generateStaticParams(){return posts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}){const {slug}=await params;const post=posts.find(p=>p.slug===slug);return post?{title:post.title+' | We Paint Siding',description:post.excerpt}:{}}
export default async function BlogPost({params}){const {slug}=await params;const p=posts.find(p=>p.slug===slug);if(!p)notFound();return <SiteHome isSupport supportKey="blog"><article className="section"><nav className="support-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/blog">Blog</a><span aria-hidden="true">/</span><span>{p.title}</span></nav><header className="blog-post-head"><p className="support-kicker">{p.category}</p><h1>{p.title}</h1><p className="support-meta">We Paint Siding · <time dateTime="2026-10-08">October 8, 2026</time> · {readingTime(p)} min read</p><p className="blog-summary">{p.excerpt}</p></header><img className="blog-post-hero" src={p.image} alt={p.alt} width="1536" height="1024" fetchPriority="high"/><p className="blog-image-note">Generated illustrative image.</p><div className="support-layout"><div className="support-prose">{p.sections.map((s,i)=><section key={s.title} id={'part-'+(i+1)}><h2>{s.title}</h2>{s.paragraphs.map(t=><p key={t}>{t}</p>)}</section>)}<p>Every property and coating system is different. Confirm the details for your own project with a qualified professional.</p><a className="text-link" href="/blog">Back to all guides</a></div><aside className="support-sidebar"><h2>In this guide</h2><nav aria-label="Article contents">{p.sections.map((s,i)=><a key={s.title} href={'#part-'+(i+1)}>{s.title}</a>)}</nav><hr/><h3>Your next step</h3><p>Explore the service that fits your project.</p><a href={p.service}>View project options</a></aside></div><div className="blog-related"><h2>More Helpful <em>Guides</em></h2><div className="blog-grid">{posts.filter(x=>x.slug!==p.slug).slice(0,3).map(post=><PostCard key={post.slug} post={post}/>)}</div></div><BlogCTA/></article></SiteHome>}
