import SiteHome,{Button} from '../components/site-home';
import '../support/support.css';
export const metadata={title:'Frequently Asked Questions | We Paint Siding',description:'Answers about exterior and cabinet painting, project preparation, quotes and service areas.'};
const groups=[['Planning your project',[
['What painting services can I explore?','Our dedicated service pages cover exterior painting and cabinet painting, with individual pages for different surfaces and cabinet components. Your final scope depends on the property and assessment.'],
['Which communities do you serve?','Explore our Locations page for the 25 communities currently listed, including the GTA, Golden Horseshoe and other Ontario service areas. Confirm availability for your property when arranging a project.'],
['How long will my project take?','Timing depends on the surfaces, condition, preparation, scope and suitable conditions. Ask for a project-specific schedule and how any changes will be communicated.'],
['How do I choose colours and finishes?','Start with the fixed materials and the look you want to achieve. Review suitable samples in the actual space and confirm the final colour, finish and product details for your project.']]],['Cabinet and exterior painting',[
['Can my existing cabinets be painted?','Material, condition and previous finishes need to be assessed. Discuss doors, drawer fronts, visible frames and panels together so the scope is clear.'],
['What preparation is included?','The appropriate preparation varies by material and existing condition. Your written scope should identify the preparation, protection and repairs included, along with any separate work required.'],
['What should I do before work begins?','Ask for instructions specific to your project, including access, belongings, pets and surrounding areas. Follow the instructions agreed with the team.'],
['Do website comparisons show client projects?','The current before and after images are generated illustrative concepts. They demonstrate possible painting transformations and are not documented client project photographs.']]],['Quotes and website features',[
['Does the online quote tool send my request?','The current tool downloads a quote request draft to your device. It does not send it to We Paint Siding or confirm a booking. Keep the file for your planning conversation.'],
['Can I subscribe to the newsletter?','Newsletter registration is not active yet. Entering an email and pressing Subscribe displays a status message without registering a subscription.'],
['Where can I read about warranties?','Ask for the terms applicable to your specific project and coating system. General website text does not establish an individual warranty.'],
['Where can I find privacy information?','The Privacy Policy and Cookies Policy explain the current forms, hosting and embedded maps. The Disclaimer provides context for guides, imagery and project descriptions.']]]];
export default function FAQ(){return <SiteHome isSupport supportKey="faq"><section className="section"><nav className="support-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>FAQ</span></nav><div className="support-intro"><h1>Your Questions. <em>Clear Answers.</em></h1><p>Helpful starting points for planning a painting project and using our website.</p></div>{groups.map(([title,items])=><section className="blog-related" key={title}><h2>{title}</h2><div className="support-faq">{items.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>)}<div className="support-cta"><div><h2>Explore your <em>Next Step.</em></h2><p>See our services, local pages and guides for more detail about your project.</p></div><Button href="/contact">Contact & Quote Options</Button></div></section></SiteHome>}
